SELECT DISTINCT
    CASE
        WHEN TIPODOC=1  THEN 'FAV'
        WHEN TIPODOC=3  THEN 'BOV'
        WHEN TIPODOC=79 THEN 'NDV'
        WHEN TIPODOC=4  THEN 'NCV'
        ELSE ' '
    END AS DOCTO,
    NUMFACT AS NUM_DOCTO,
    SUBSTRING(CHOI_DB.DESCRIP,1,25) AS TIPO_VTA,
    docu_db.FECHA AS FECHA_EMISION,
    VENCIMIE AS FECHA_VENCIMIE,
    perso_db.codigo AS COD_VDDOR,
    perso_db.nombre AS NOM_VDDOR,
    perso_db.apellido AS APELL_VDDOR,
    DATENAME(M, docu_db.FECHA) AS MES,
    rut,
    SUBSTRING(razsoc2,1,40) AS CLIENTE,
    clien_db.clase1 AS TIPO_CLIENTE,
    art_db.codigo AS COD_ARTICULO,
    SUBSTRING(docde_db.descrip,1,45) AS PRODUCTO,
    (SELECT codigo FROM CHOI_DB WHERE art_db.CLASE1=CHOI_DB.DESCRIP AND tipo=6) AS CodClase1,
    art_db.CLASE1,
    (SELECT codigo FROM CHOI_DB WHERE art_db.CLASE2=CHOI_DB.DESCRIP AND tipo=7) AS CodClase2,
    art_db.CLASE2,
    CASE WHEN TIPODOC=4 THEN docde_db.cantidad*-1 ELSE docde_db.CANTIDAD END AS CANTIDAD,
    unidmed,
    monevta,
    DOCDE_DB.precunit AS PRECIO_VTA_BASE,
    TASACBIO AS TCAMBIO,
    DOCDE_DB.DESCTO AS PCT_DESCTO_LINEA,
    DOCDE_DB.PRECUNIT*TASACBIO - DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100) AS DESCTO_LINEA_PESOS,
    DOCDE_DB.PRECUNIT*TASACBIO - DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCU_DB.DCTOPJE/100) AS DESCTO_PORTADA_PESOS,
    ((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100)) AS PRECIO_VTA_UNIT,
    VALPROM AS CTO_PROM_UNIT,
    COSTOREP AS CTO_REPOS_UNIT,
    PULTCOM AS CTO_ULT_COMPRA_UNIT,
    DOCDE_DB.cantidad*((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100)) AS TOTAL_NETO,
    CANTIDAD*VALPROM AS CTO_PROMEDIO_TOTAL,
    CANTIDAD*COSTOREP AS CTO_REPOS_TOTAL,
    CANTIDAD*PULTCOM AS CTO_ULT_COMPRA_TOTAL,
    CASE WHEN TIPODOC=4 THEN
        DOCDE_DB.CANTIDAD*-1*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-VALPROM)
    ELSE
        DOCDE_DB.CANTIDAD*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-VALPROM)
    END AS RESULTADO_CTO_PROM,
    CASE WHEN TIPODOC=4 THEN
        DOCDE_DB.CANTIDAD*-1*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-COSTOREP)
    ELSE
        DOCDE_DB.CANTIDAD*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-COSTOREP)
    END AS RESULTADO_CTO_REPOS,
    CASE WHEN TIPODOC=4 THEN
        DOCDE_DB.CANTIDAD*-1*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-PULTCOM)
    ELSE
        DOCDE_DB.CANTIDAD*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-PULTCOM)
    END AS RESULTADO_CTO_ULT_COMPRA,

    -- Trazabilidad: Nota de Venta de la que proviene cada línea y, en las
    -- notas de crédito, la factura a la que hacen referencia (ver NV_DOC).
    NV_DOC.NOTA_VENTA AS NOTA_VENTA,
    NV_DOC.FACTURA_REF AS FACTURA_REF

FROM art_db, PLAN_DB,
    docde_db LEFT OUTER JOIN cent_db ON docde_db.cencosto = cent_db.nreguist
             LEFT OUTER JOIN (
        -- Resuelve la Nota de Venta de cada línea de documento, en este orden:
        --   1. SQNVDET  -> línea de la NV (NOTDE_DB.SEQNVDET) -> NOTV_DB.NUMNOTA
        --   2. SQGDDET  -> guía de despacho de origen (DOCU_DB.NUMREG) -> su NROPEDIDO
        --   3. NROPEDIDO de la cabecera del documento
        --   4. Notas de crédito: NUMFV es el NUMREG de la factura referenciada
        --      -> NROPEDIDO de esa factura
        --   5. Notas de crédito: NV más frecuente entre las guías de esa factura
        -- NROPEDIDO es varchar en Manager; por eso se limpia y se convierte.
        SELECT
            dd.SEQLINE,
            COALESCE(
                nvl.NUMNOTA,
                TRY_CONVERT(int, NULLIF(LTRIM(RTRIM(g.NROPEDIDO)), '')),
                TRY_CONVERT(int, NULLIF(LTRIM(RTRIM(d.NROPEDIDO)), '')),
                TRY_CONVERT(int, NULLIF(LTRIM(RTRIM(fr.NROPEDIDO)), '')),
                frg.NOTA_VENTA
            ) AS NOTA_VENTA,
            CAST(fr.NUMFACT AS bigint) AS FACTURA_REF
        FROM DOCU_DB d
        INNER JOIN DOCDE_DB dd ON dd.NUMRECOR = d.NUMREG
        LEFT JOIN NOTDE_DB nd  ON dd.SQNVDET <> 0 AND nd.SEQNVDET = dd.SQNVDET
        LEFT JOIN NOTV_DB  nvl ON nvl.NUMREG = nd.NUMRECOR
        LEFT JOIN DOCU_DB  g   ON dd.SQGDDET <> 0 AND g.NUMREG = dd.SQGDDET AND g.TIPODOC = 2
        LEFT JOIN DOCU_DB  fr  ON d.TIPODOC = 4 AND ISNULL(d.NUMFV, 0) <> 0 AND fr.NUMREG = d.NUMFV
        OUTER APPLY (
            SELECT TOP 1 TRY_CONVERT(int, NULLIF(LTRIM(RTRIM(g2.NROPEDIDO)), '')) AS NOTA_VENTA
            FROM DOCDE_DB dd2
            INNER JOIN DOCU_DB g2 ON g2.NUMREG = dd2.SQGDDET AND g2.TIPODOC = 2
            WHERE fr.NUMREG IS NOT NULL
              AND dd2.NUMRECOR = fr.NUMREG
              AND dd2.SQGDDET <> 0
              AND NULLIF(LTRIM(RTRIM(g2.NROPEDIDO)), '') IS NOT NULL
            GROUP BY TRY_CONVERT(int, NULLIF(LTRIM(RTRIM(g2.NROPEDIDO)), ''))
            ORDER BY COUNT(*) DESC
        ) frg
        WHERE d.TIPODOC IN (1, 3, 4, 79, 146)
          AND d.FECHA >= CONVERT(datetime, '01/01/{AÑO_ACTUAL}', 103)
          AND d.FECHA <= CONVERT(datetime, '31/12/{AÑO_ACTUAL}', 103)
    ) NV_DOC ON NV_DOC.SEQLINE = docde_db.SEQLINE,
    DOCU_DB LEFT OUTER JOIN CHOI_DB ON DOCU_DB.TIPOVTA = CHOI_DB.NUMREG
            LEFT OUTER JOIN PERSO_DB ON perso_db.numreg = docu_db.codvend
            LEFT OUTER JOIN CLIEN_DB ON docu_db.nrutclie = clien_db.nreguist

WHERE (tipodoc IN (1, 3, 4, 79, 146))
  AND docu_db.numreg = docde_db.numrecor
  AND docde_db.ncodart = art_db.nreguist
  AND DOCDE_DB.CTACTBLE = PLAN_DB.NREGUIST
  AND ART_DB.CODIGO <> '-'
  AND fecha >= CONVERT(datetime, '01/01/{AÑO_ACTUAL}', 103)
  AND fecha <= CONVERT(datetime, '31/12/{AÑO_ACTUAL}', 103)
ORDER BY NUMFACT
