SELECT DISTINCT
    CASE
        WHEN TIPODOC=1  THEN 'FAV'
        WHEN TIPODOC=3  THEN 'BOV'
        WHEN TIPODOC=79 THEN 'NDV'
        WHEN TIPODOC=4  THEN 'NCV'
        ELSE ' '
    END AS DOCTO,
    NUMFACT AS NUM_DOCTO,
    SUBSTRING(CHOI_DB.DESCRIP,1,25) AS TIPO_VTA,
    docu_db.FECHA AS FECHA_EMISION,
    VENCIMIE AS FECHA_VENCIMIE,
    perso_db.codigo AS COD_VDDOR,
    perso_db.nombre AS NOM_VDDOR,
    perso_db.apellido AS APELL_VDDOR,
    DATENAME(M, docu_db.FECHA) AS MES,
    rut,
    SUBSTRING(razsoc2,1,40) AS CLIENTE,
    clien_db.clase1 AS TIPO_CLIENTE,
    art_db.codigo AS COD_ARTICULO,
    SUBSTRING(docde_db.descrip,1,45) AS PRODUCTO,
    (SELECT codigo FROM CHOI_DB WHERE art_db.CLASE1=CHOI_DB.DESCRIP AND tipo=6) AS CodClase1,
    art_db.CLASE1,
    (SELECT codigo FROM CHOI_DB WHERE art_db.CLASE2=CHOI_DB.DESCRIP AND tipo=7) AS CodClase2,
    art_db.CLASE2,
    CASE WHEN TIPODOC=4 THEN docde_db.cantidad*-1 ELSE docde_db.CANTIDAD END AS CANTIDAD,
    unidmed,
    monevta,
    DOCDE_DB.precunit AS PRECIO_VTA_BASE,
    TASACBIO AS TCAMBIO,
    DOCDE_DB.DESCTO AS PCT_DESCTO_LINEA,
    DOCDE_DB.PRECUNIT*TASACBIO - DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100) AS DESCTO_LINEA_PESOS,
    DOCDE_DB.PRECUNIT*TASACBIO - DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCU_DB.DCTOPJE/100) AS DESCTO_PORTADA_PESOS,
    ((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100)) AS PRECIO_VTA_UNIT,
    VALPROM AS CTO_PROM_UNIT,
    COSTOREP AS CTO_REPOS_UNIT,
    PULTCOM AS CTO_ULT_COMPRA_UNIT,
    DOCDE_DB.cantidad*((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100)) AS TOTAL_NETO,
    CANTIDAD*VALPROM AS CTO_PROMEDIO_TOTAL,
    CANTIDAD*COSTOREP AS CTO_REPOS_TOTAL,
    CANTIDAD*PULTCOM AS CTO_ULT_COMPRA_TOTAL,
    CASE WHEN TIPODOC=4 THEN
        DOCDE_DB.CANTIDAD*-1*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-VALPROM)
    ELSE
        DOCDE_DB.CANTIDAD*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-VALPROM)
    END AS RESULTADO_CTO_PROM,
    CASE WHEN TIPODOC=4 THEN
        DOCDE_DB.CANTIDAD*-1*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-COSTOREP)
    ELSE
        DOCDE_DB.CANTIDAD*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-COSTOREP)
    END AS RESULTADO_CTO_REPOS,
    CASE WHEN TIPODOC=4 THEN
        DOCDE_DB.CANTIDAD*-1*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-PULTCOM)
    ELSE
        DOCDE_DB.CANTIDAD*(((DOCDE_DB.PRECUNIT*TASACBIO-((DOCDE_DB.PRECUNIT*TASACBIO-DOCDE_DB.PRECUNIT*TASACBIO*(1-DOCDE_DB.DESCTO/100))))*(1-DOCU_DB.DCTOPJE/100))-PULTCOM)
    END AS RESULTADO_CTO_ULT_COMPRA

FROM art_db, PLAN_DB,
    docde_db LEFT OUTER JOIN cent_db ON docde_db.cencosto = cent_db.nreguist,
    DOCU_DB LEFT OUTER JOIN CHOI_DB ON DOCU_DB.TIPOVTA = CHOI_DB.NUMREG
            LEFT OUTER JOIN PERSO_DB ON perso_db.numreg = docu_db.codvend
            LEFT OUTER JOIN CLIEN_DB ON docu_db.nrutclie = clien_db.nreguist

WHERE (tipodoc IN (1, 3, 4, 79, 146))
  AND docu_db.numreg = docde_db.numrecor
  AND docde_db.ncodart = art_db.nreguist
  AND DOCDE_DB.CTACTBLE = PLAN_DB.NREGUIST
  AND ART_DB.CODIGO <> '-'
  AND fecha >= CONVERT(datetime, '01/01/{AÑO_ACTUAL}', 103)
  AND fecha <= CONVERT(datetime, '31/12/{AÑO_ACTUAL}', 103)
ORDER BY NUMFACT